### ISSUE TITLE
Bootstrap step fails if generator is not make

### ISSUE THREAD

**Issue by awvwgk** [qcscine/puffin#1]
Trying to bootstrap puffin fails if ninja is chosen as generator.

**Config file excerpt**

```yaml
programs:
  utils:
    available: true
    cmake_flags: '-GNinja'
    cxx_compiler_flags: ''
    march: ''
    root: ''
    source: https://github.com/qcscine/utilities.git
    version: master
```

**Error message**

```
make: *** No rule to make target 'install'.  Stop.
Traceback (most recent call last):
  File "/opt/conda/envs/scine/lib/python3.10/runpy.py", line 196, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "/opt/conda/envs/scine/lib/python3.10/runpy.py", line 86, in _run_code
    exec(code, run_globals)
  File "/opt/conda/envs/scine/lib/python3.10/site-packages/scine_puffin/__main__.py", line 156, in <module>
    main()
  File "/opt/conda/envs/scine/lib/python3.10/site-packages/scine_puffin/__main__.py", line 142, in main
    main_bootstrap(config)
  File "/opt/conda/envs/scine/lib/python3.10/site-packages/scine_puffin/__main__.py", line 74, in main_bootstrap
    bootstrap(config)
  File "/opt/conda/envs/scine/lib/python3.10/site-packages/scine_puffin/bootstrap.py", line 51, in bootstrap
    utils.install(utils_build_dir, install_dir, config["resources"]["cores"])
  File "/opt/conda/envs/scine/lib/python3.10/site-packages/scine_puffin/programs/utils.py", line 25, in install
    self.scine_module_install(repo_dir, install_dir, ncores)
  File "/opt/conda/envs/scine/lib/python3.10/site-packages/scine_puffin/programs/program.py", line 151, in scine_module_install
    subprocess.run(["make", "-j" + str(ncores), "install"], env=env, check=True)
  File "/opt/conda/envs/scine/lib/python3.10/subprocess.py", line 524, in run
    raise CalledProcessError(retcode, process.args,
subprocess.CalledProcessError: Command '['make', '-j1', 'install']' returned non-zero exit status 2.
```

**Comment by weymutht** [comment]
Does it work if you use a different generator, e.g. standard Unix Makefiles?

**Comment by awvwgk** [comment]
Probably, but it will be slow.
